### ISSUE TITLE
Unable to build the project after adding a new static asset

### ISSUE THREAD

**Issue by samithaf** [brentvatne/ejected-example-fonts#1]
Steps to reproduce: 
- Add a simple PNG image to assets folder
- Import the new image in App.tsx file
- Try to do a release build on either iOS or Android
- Build fails

More details about the issue: https://forums.expo.io/t/ios-bundle-assets-error-when-building-release-403/36616

**Comment by brentvatne** [comment]
I can't reproduce this

I did the following (from current master as of time of posting):
- ran `expo publish`
- ran release build
- worked
- copied an example.png into assets
- added an image displaying that in App.tsx
- built a debug build, confirmed it worked as expected
- ran `expo publish`
- ran release build
- worked

**Comment by brentvatne** [comment]
the problem described in the forums post you link to was easy to reproduce however! i have a fix for it here: https://github.com/expo/expo-cli/pull/1999 - it will be deployed shortly, see the forums thread for an update when that occurs

**Comment by samithaf** [comment]
Thank you! fix is working
